### PR TITLE
main to this branch

### PR DESCRIPTION
**Pull request by catorghans**
First pull request from main to this branch. Then the other way around.

### CODE REVIEW

**Comment by jkva** [comment]
Why would you not rebase your branch onto `origin/main` instead?

**Comment by catorghans** [comment]
Possible, but I don't like changing the history of git branches. It feels contrary to why you use git in the first place.

**Comment by jkva** [comment]
Agreed when it comes to the main branch. When it's a branch that only you work on? Rebase and force push. Alternatively, `git pull` and fast-forward. Pull requests from `main` into feature branches is a smell.

**Comment by catorghans** [comment]
ok, will close this PR and do

git fetch
git rebase origin/master

within this branch

**Pull request closed without merging**
